services:

  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    environment:
      EULA: "TRUE"
      LEVEL_NAME: survivalsmp
      OPS: "2533274840945594, 2535465719343630"
      ALLOW_CHEATS: true
      ALLOW_LIST: false
      CLIENT_SIDE_CHUNK_GENERATION_ENABLED: false
      MAX_THREADS: 0
      VIEW_DISTANCE: 20
      SERVER_NAME: "Heilige Tomatenserver"
      ENABLE_SSH: true
    ports:
      - "19132:19132/udp"
    volumes:
      - ./bdr-data:/data
    stdin_open: true
    tty: true
    expose:
      - 2222

  backup:
    container_name: backup
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      minecraft:
        condition: service_healthy
    volumes:
      - ./backups:/backups
      - ./bdr-data:/bdr-data

  websocket:
    container_name: websocket
    image: joanroig/admincraft-websocket:latest
    restart: always
    depends_on:
      minecraft:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./certs:/usr/src/app/certs:ro
    environment:
      SECRET_KEY: 7VHKHrngbqrAvxrrDM4v4kjMtkhjhqK6RjvuzhTmNH4EaqbesTLBrna82ZGgiYf4
      USE_SSL: false

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: 2G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data

  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: minecraft
      DEBUG: "true"
    depends_on:
      - minecraft

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor

  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus


volumes:
  mc-data: {}
  bdr-data: {}
  prometheus-tsdb: {}
  grafana-lib: {}