{
 "title": "BDR Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(server_host)" } }
  ]
 },
 "panels": [
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_healthy{server_host=\"$server\",server_version=~\".+\"}",
     "legendFormat": "{{server_host}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count{server_host=\"$server\"}",
     "legendFormat": "online"
    },
    {
     "expr": "minecraft_status_players_max_count{server_host=\"$server\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Minecraft Service - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container_label_com_docker_compose_service=\"$server\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Minecraft Service - Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"$server\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}